//MESSAGES PAGE TYPES
export const SEND_UPDATE_MESSAGE = 'SEND_UPDATE_MESSAGE'
export const GET_MESSAGES_BY_ID = 'GET_MESSAGES_BY_ID'
export const GET_USERS = 'GET_USERS'
export const REQUEST_LOADING_MSG = 'REQUEST_LOADING_MSG'
export const REQUEST_LOADING_USERS = 'REQUEST_LOADING_USERS'
export const DISABLE_INPUT_BTN = 'DISABLE_INPUT_BTN'
export const ERROR_MESSAGE = 'ERROR_MESSAGE'

//PROFILE PAGE TYPES
export const ADD_SHARE = 'ADD_SHARE'
export const GET_USER = 'GET_USER'
export const GET_USER_POSTS = 'GET_USER_POSTS'
export const REQUEST_LOADING_POST = 'REQUEST_LOADING_POST'
export const REQUEST_LOADING_USER = 'REQUEST_LOADING_USER'
export const USER_ID = 'USER_ID'
//LOGIN PAGE TYPES
export const IS_AUTH = 'IS_AUTH'
export const GET_USER_HEADER = 'GET_USER_HEADER'